module Proto.Algorithm exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/algorithm.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias Algorithm =
    { id : String -- 1
    , accountId : String -- 2
    , status : String -- 3
    , code : String -- 4
    , description : String -- 5
    }


algorithmDecoder : JD.Decoder Algorithm
algorithmDecoder =
    JD.lazy <| \_ -> decode Algorithm
        |> required "Id" JD.string ""
        |> required "AccountId" JD.string ""
        |> required "Status" JD.string ""
        |> required "Code" JD.string ""
        |> required "Description" JD.string ""


algorithmEncoder : Algorithm -> JE.Value
algorithmEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Id" JE.string "" v.id)
        , (requiredFieldEncoder "AccountId" JE.string "" v.accountId)
        , (requiredFieldEncoder "Status" JE.string "" v.status)
        , (requiredFieldEncoder "Code" JE.string "" v.code)
        , (requiredFieldEncoder "Description" JE.string "" v.description)
        ]
