module Proto.Algolog exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/algolog.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias Algolog =
    { algorithmId : String -- 1
    , level : String -- 2
    , message : String -- 3
    }


algologDecoder : JD.Decoder Algolog
algologDecoder =
    JD.lazy <| \_ -> decode Algolog
        |> required "AlgorithmId" JD.string ""
        |> required "Level" JD.string ""
        |> required "Message" JD.string ""


algologEncoder : Algolog -> JE.Value
algologEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "AlgorithmId" JE.string "" v.algorithmId)
        , (requiredFieldEncoder "Level" JE.string "" v.level)
        , (requiredFieldEncoder "Message" JE.string "" v.message)
        ]
