module Proto.Algorithm_list_response exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/algorithm_list_response.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE
import Proto.Algorithm exposing (..)


type alias AlgorithmListResponse =
    { ok : Bool -- 1
    , message : String -- 2
    , algorithms : List Algorithm -- 3
    }


algorithmListResponseDecoder : JD.Decoder AlgorithmListResponse
algorithmListResponseDecoder =
    JD.lazy <| \_ -> decode AlgorithmListResponse
        |> required "Ok" JD.bool False
        |> required "Message" JD.string ""
        |> repeated "Algorithms" algorithmDecoder


algorithmListResponseEncoder : AlgorithmListResponse -> JE.Value
algorithmListResponseEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Ok" JE.bool False v.ok)
        , (requiredFieldEncoder "Message" JE.string "" v.message)
        , (repeatedFieldEncoder "Algorithms" algorithmEncoder v.algorithms)
        ]
