module Proto.Algolog_list exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/algolog_list.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias AlgologList =
    { algorunId : String -- 1
    }


algologListDecoder : JD.Decoder AlgologList
algologListDecoder =
    JD.lazy <| \_ -> decode AlgologList
        |> required "AlgorunId" JD.string ""


algologListEncoder : AlgologList -> JE.Value
algologListEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "AlgorunId" JE.string "" v.algorunId)
        ]
