module Proto.Algorithm_detail_response exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/algorithm_detail_response.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE
import Proto.Algorithm exposing (..)


type alias AlgorithmDetailResponse =
    { ok : Bool -- 1
    , message : String -- 2
    , algorithm : Maybe Algorithm -- 3
    }


algorithmDetailResponseDecoder : JD.Decoder AlgorithmDetailResponse
algorithmDetailResponseDecoder =
    JD.lazy <| \_ -> decode AlgorithmDetailResponse
        |> required "Ok" JD.bool False
        |> required "Message" JD.string ""
        |> optional "Algorithm" algorithmDecoder


algorithmDetailResponseEncoder : AlgorithmDetailResponse -> JE.Value
algorithmDetailResponseEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Ok" JE.bool False v.ok)
        , (requiredFieldEncoder "Message" JE.string "" v.message)
        , (optionalEncoder "Algorithm" algorithmEncoder v.algorithm)
        ]
