module Proto.Lambda_response exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/lambda_response.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias LambdaResponse =
    { token : String -- 1
    , stateOut : String -- 2
    }


lambdaResponseDecoder : JD.Decoder LambdaResponse
lambdaResponseDecoder =
    JD.lazy <| \_ -> decode LambdaResponse
        |> required "Token" JD.string ""
        |> required "StateOut" JD.string ""


lambdaResponseEncoder : LambdaResponse -> JE.Value
lambdaResponseEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Token" JE.string "" v.token)
        , (requiredFieldEncoder "StateOut" JE.string "" v.stateOut)
        ]
