module Proto.Market_price exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/market_price.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias MarketPrice =
    { exchange : String -- 1
    , market : String -- 2
    , amount : String -- 3
    , currency : String -- 4
    , receivedAt : String -- 5
    }


marketPriceDecoder : JD.Decoder MarketPrice
marketPriceDecoder =
    JD.lazy <| \_ -> decode MarketPrice
        |> required "Exchange" JD.string ""
        |> required "Market" JD.string ""
        |> required "Amount" JD.string ""
        |> required "Currency" JD.string ""
        |> required "ReceivedAt" JD.string ""


marketPriceEncoder : MarketPrice -> JE.Value
marketPriceEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Exchange" JE.string "" v.exchange)
        , (requiredFieldEncoder "Market" JE.string "" v.market)
        , (requiredFieldEncoder "Amount" JE.string "" v.amount)
        , (requiredFieldEncoder "Currency" JE.string "" v.currency)
        , (requiredFieldEncoder "ReceivedAt" JE.string "" v.receivedAt)
        ]
