module Proto.Notify_response exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/notify_response.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias NotifyResponse =
    { ok : Bool -- 1
    , errMessage : String -- 2
    , messageId : String -- 3
    }


notifyResponseDecoder : JD.Decoder NotifyResponse
notifyResponseDecoder =
    JD.lazy <| \_ -> decode NotifyResponse
        |> required "Ok" JD.bool False
        |> required "ErrMessage" JD.string ""
        |> required "MessageId" JD.string ""


notifyResponseEncoder : NotifyResponse -> JE.Value
notifyResponseEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Ok" JE.bool False v.ok)
        , (requiredFieldEncoder "ErrMessage" JE.string "" v.errMessage)
        , (requiredFieldEncoder "MessageId" JE.string "" v.messageId)
        ]
