module Proto.Schedule_create_response exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/schedule_create_response.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias ScheduleCreateResponse =
    { ok : Bool -- 1
    , message : String -- 2
    }


scheduleCreateResponseDecoder : JD.Decoder ScheduleCreateResponse
scheduleCreateResponseDecoder =
    JD.lazy <| \_ -> decode ScheduleCreateResponse
        |> required "Ok" JD.bool False
        |> required "Message" JD.string ""


scheduleCreateResponseEncoder : ScheduleCreateResponse -> JE.Value
scheduleCreateResponseEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Ok" JE.bool False v.ok)
        , (requiredFieldEncoder "Message" JE.string "" v.message)
        ]
