module Proto.Schedule_stop_response exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/schedule_stop_response.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias ScheduleStopResponse =
    { ok : Bool -- 1
    , message : String -- 2
    }


scheduleStopResponseDecoder : JD.Decoder ScheduleStopResponse
scheduleStopResponseDecoder =
    JD.lazy <| \_ -> decode ScheduleStopResponse
        |> required "Ok" JD.bool False
        |> required "Message" JD.string ""


scheduleStopResponseEncoder : ScheduleStopResponse -> JE.Value
scheduleStopResponseEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Ok" JE.bool False v.ok)
        , (requiredFieldEncoder "Message" JE.string "" v.message)
        ]
