module Proto.Schedule_start exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/schedule_start.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias ScheduleStart =
    { scheduleId : String -- 1
    }


scheduleStartDecoder : JD.Decoder ScheduleStart
scheduleStartDecoder =
    JD.lazy <| \_ -> decode ScheduleStart
        |> required "ScheduleId" JD.string ""


scheduleStartEncoder : ScheduleStart -> JE.Value
scheduleStartEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "ScheduleId" JE.string "" v.scheduleId)
        ]
