module Proto.Schedule_detail_response exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/schedule_detail_response.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE
import Proto.Schedule exposing (..)


type alias ScheduleDetailResponse =
    { ok : Bool -- 1
    , message : String -- 2
    , schedule : Maybe Schedule -- 3
    }


scheduleDetailResponseDecoder : JD.Decoder ScheduleDetailResponse
scheduleDetailResponseDecoder =
    JD.lazy <| \_ -> decode ScheduleDetailResponse
        |> required "Ok" JD.bool False
        |> required "Message" JD.string ""
        |> optional "Schedule" scheduleDecoder


scheduleDetailResponseEncoder : ScheduleDetailResponse -> JE.Value
scheduleDetailResponseEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Ok" JE.bool False v.ok)
        , (requiredFieldEncoder "Message" JE.string "" v.message)
        , (optionalEncoder "Schedule" scheduleEncoder v.schedule)
        ]
