module Proto.Schedule_run exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/schedule_run.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE
import Proto.Schedule exposing (..)
import Proto.Algorun exposing (..)


type alias ScheduleRun =
    { schedule : Maybe Schedule -- 1
    , run : Maybe Algorun -- 2
    }


scheduleRunDecoder : JD.Decoder ScheduleRun
scheduleRunDecoder =
    JD.lazy <| \_ -> decode ScheduleRun
        |> optional "Schedule" scheduleDecoder
        |> optional "Run" algorunDecoder


scheduleRunEncoder : ScheduleRun -> JE.Value
scheduleRunEncoder v =
    JE.object <| List.filterMap identity <|
        [ (optionalEncoder "Schedule" scheduleEncoder v.schedule)
        , (optionalEncoder "Run" algorunEncoder v.run)
        ]
