-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/schedule.proto

module Proto.Schedule exposing (..)

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias Schedule =
    { id : String -- 1
    , accountId : String -- 2
    , algorithmId : String -- 3
    , status : String -- 4
    , initialState : String -- 5
    }


scheduleDecoder : JD.Decoder Schedule
scheduleDecoder =
    JD.lazy <| \_ -> decode Schedule
        |> required "Id" JD.string ""
        |> required "AccountId" JD.string ""
        |> required "AlgorithmId" JD.string ""
        |> required "Status" JD.string ""
        |> required "InitialState" JD.string ""


scheduleEncoder : Schedule -> JE.Value
scheduleEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Id" JE.string "" v.id)
        , (requiredFieldEncoder "AccountId" JE.string "" v.accountId)
        , (requiredFieldEncoder "AlgorithmId" JE.string "" v.algorithmId)
        , (requiredFieldEncoder "Status" JE.string "" v.status)
        , (requiredFieldEncoder "InitialState" JE.string "" v.initialState)
        ]
