-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/session_create.proto

module Proto.Session_create exposing (..)

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE
import Proto.Account exposing (..)


type alias SessionCreate =
    { token : String -- 1
    }


sessionCreateDecoder : JD.Decoder SessionCreate
sessionCreateDecoder =
    JD.lazy <| \_ -> decode SessionCreate
        |> required "Token" JD.string ""


sessionCreateEncoder : SessionCreate -> JE.Value
sessionCreateEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Token" JE.string "" v.token)
        ]
