-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/signin_email_response.proto

module Proto.Signin_email_response exposing (..)

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias SigninEmailResponse =
    { ok : Bool -- 1
    , message : String -- 2
    }


signinEmailResponseDecoder : JD.Decoder SigninEmailResponse
signinEmailResponseDecoder =
    JD.lazy <| \_ -> decode SigninEmailResponse
        |> required "Ok" JD.bool False
        |> required "Message" JD.string ""


signinEmailResponseEncoder : SigninEmailResponse -> JE.Value
signinEmailResponseEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Ok" JE.bool False v.ok)
        , (requiredFieldEncoder "Message" JE.string "" v.message)
        ]
