module Proto.Signin_email exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/signin_email.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias SigninEmail =
    { email : String -- 1
    }


signinEmailDecoder : JD.Decoder SigninEmail
signinEmailDecoder =
    JD.lazy <| \_ -> decode SigninEmail
        |> required "Email" JD.string ""


signinEmailEncoder : SigninEmail -> JE.Value
signinEmailEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Email" JE.string "" v.email)
        ]
