module Proto.Tick_tock exposing (..)

-- DO NOT EDIT
-- AUTOGENERATED BY THE ELM PROTOCOL BUFFER COMPILER
-- https://github.com/tiziano88/elm-protobuf
-- source file: proto/tick_tock.proto

import Protobuf exposing (..)

import Json.Decode as JD
import Json.Encode as JE


type alias TickTock =
    { time : String -- 1
    }


tickTockDecoder : JD.Decoder TickTock
tickTockDecoder =
    JD.lazy <| \_ -> decode TickTock
        |> required "Time" JD.string ""


tickTockEncoder : TickTock -> JE.Value
tickTockEncoder v =
    JE.object <| List.filterMap identity <|
        [ (requiredFieldEncoder "Time" JE.string "" v.time)
        ]
